### ISSUE TITLE
Cannot generate certificate due to openssl error

### ISSUE THREAD

**Issue by thibmaek** [latentflip/dev-cert-authority#3]
Node: v6.6.0
latest version of this tool

<img width="1337" alt="screen shot 2016-09-25 at 15 33 51" src="https://cloud.githubusercontent.com/assets/6213695/18815546/9188488e-8335-11e6-8aa9-a0d6d6209350.png">

**Comment by latentflip** [comment]
- What os + version are you on?
- What version of openssl does your machine have? (`openssl version`)
- If you run the openssl command manually (the bit after `Command failed:` in the error output) what error is listed?

Thanks

**Comment by thibmaek** [comment]
macOS Sierra, OpenSSL 0.9.8zh 14 Jan 2016, no error listed when running command manually.
